[features]
test_input = []

[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13.*"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
